### ISSUE TITLE
UpTime #17 failed

### ISSUE THREAD

**Issue by ishland** [xiaoyaoge233/upTime#1]
Build 'UpTime' is failing!

Last 50 lines of build output:

```
Started by user ishland
Building on master in workspace /var/lib/jenkins/workspace/UpTime
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
Cloning the remote Git repository
Cloning repository https://github.com/xiaoyaoge233/upTime.git
 > git init /var/lib/jenkins/workspace/UpTime # timeout=10
Fetching upstream changes from https://github.com/xiaoyaoge233/upTime.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/xiaoyaoge233/upTime.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com/xiaoyaoge233/upTime.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/xiaoyaoge233/upTime.git # timeout=10
Fetching upstream changes from https://github.com/xiaoyaoge233/upTime.git
 > git fetch --tags --progress https://github.com/xiaoyaoge233/upTime.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/xiaoyaoge233/upTime.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:888)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1155)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
	at hudson.scm.SCM.checkout(SCM.java:504)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
	at hudson.model.Run.execute(Run.java:1815)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/xiaoyaoge233/upTime.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://github.com/xiaoyaoge233/upTime.git/': Empty reply from server

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2016)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1735)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:420)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:886)
	... 11 more
ERROR: Error fetching remote repo 'origin'

```

Changes since last successful build:
No changes

[View full output](https://jenkins-ssl.ishland.site/job/UpTime/17/)

**Comment by ishland** [comment]
Build was fixed!
